version: '3'
services:
    ### Admin-panel
    admin-nginx:
        build:
            context: ./
            dockerfile: ${PWD}/admin/docker/nginx.docker
        volumes:
            - ./admin:/app
            - ./admin/docker/nginx/ssl:/etc/nginx/ssl
        depends_on:
            - admin-php-fpm
        ports:
            - "7777:443"
    admin-php-fpm:
        build:
            context: ./
            dockerfile: ${PWD}/admin/docker/php-fpm.docker
        volumes:
            - ./admin:/app
        depends_on:
            - service-mysql
    admin-encore:
        build:
            context: ./
            dockerfile: ${PWD}/admin/docker/encore.docker
        volumes:
            - ./admin:/app
    ### Api
    api-nginx:
        build:
            context: ./
            dockerfile: ${PWD}/api/docker/nginx.docker
        volumes:
            - ./api:/app
            - ./api/docker/nginx/ssl:/etc/nginx/ssl
        depends_on:
            - api-php-fpm
        ports:
            - "9999:443"
    api-php-fpm:
        build:
            context: ./
            dockerfile: ${PWD}/api/docker/php-fpm.docker
        volumes:
            - ./api:/app
        depends_on:
            - service-mysql
    ### Database
    service-mysql:
        image: mysql:5.7
        volumes:
            - ${PWD}/storage/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=app"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=app"
        ports:
            - "33061:3306"
    ### Client
    service-client:
        build:
            context: ./
            dockerfile: ${PWD}/client/docker/client.docker
        volumes:
            - ./client:/app
            - ./client/docker/nginx/ssl:/etc/nginx/ssl
        ports:
            - '8080:443'