#!/bin/bash

echo "Startinitialization server"


sudo apt-get update
sudo apt-get install curl
curl --version
echo "Curl is ready"


sudo apt -y update
sudo apt -y install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt update
sudo apt -y install docker-ce docker-ce-cli containerd.io
sudo usermod -aG docker $USER
newgrp docker
version_d = docker version
echo "Docker is ready, version $version_d"


sudo apt -y update
sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
version_dc = docker-compose --version
echo "Docker compose is ready, version $version_dc"



echo "Finish !!!"